---
- id: pre-commit-sync
  name: pre-commit-sync
  description: Sync pre-commit versions from lock files
  entry: pre-commit-sync
  args: [-w]
  language: python
  language_version: python3
  files: |
    (?x)^(
        .pre-commit-hooks.yaml|
        .pre-commit-config.yaml|
        poetry.lock|
        yarn.lock
    )$
