---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
      - id: pretty-format-json
        args: [--autofix, --indent=2]
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  - repo: https://github.com/miki725/importanize
    rev: 0.8.0-alpha1
    hooks:
      - id: importanize
        args: [-v]
        language_version: python3

  - repo: https://github.com/python/black
    rev: 22.6.0
    hooks:
      - id: black
